name: Test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          git config --global url."https://${{secrets.GO_MODULES_TOKEN}}:x-oauth-basic@github.com/witalok2".insteadOf "https://github.com/witalok2"
          go get -v -t -d ./...
          git submodule update --init --recursive --remote

      - name: Test
        run:  make test
